name: Deploy Next.js Docker to VPS

on:
  push:
    branches:
      - main  # Deploy khi push code lên main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "."
          target: "/home/petd-git/spring-be/src-be"

      - name: SSH vào VPS và deploy Docker
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/petd-git/spring-be/src-be
            
            # Pull latest code from the repository
            git pull origin main
            
            docker stop spring-be-connect
            docker rm spring-be-connect
            docker rmi spring-be-connect-ig
            
            docker build -t spring-be-connect-ig .
            docker run -d --name spring-be-connect -p 8082:8082 spring-be-connect-ig
            
            docker container prune -f
            docker image prune -a -f

            
            
            


